# Generated by Django 2.2.12 on 2020-05-28 03:21

import autoslug.fields
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('etat_civile', models.CharField(max_length=100, null=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=255, null=True)),
                ('date', models.DateField(null=True)),
                ('activite', models.CharField(max_length=100, null=True)),
                ('date_obtention_de_diplome', models.DateField(null=True)),
                ('adresse_professionnelle', models.CharField(max_length=255, null=True)),
                ('ville_exercice', models.CharField(max_length=255, null=True)),
                ('pays', models.CharField(max_length=255, null=True)),
                ('telephone', models.CharField(max_length=255, null=True)),
                ('gsm', models.CharField(max_length=255, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joind')),
                ('profile_pic', models.ImageField(blank=True, default='profile-img.png', null=True, upload_to='')),
                ('etat', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Last Login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('tel', models.CharField(max_length=100, null=True)),
                ('fax', models.CharField(max_length=100, null=True)),
                ('adress', models.CharField(max_length=100, null=True)),
                ('ville', models.CharField(max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmcie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('ville', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, default='profile-img.png', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, null=True, verbose_name='titre')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='titre', unique=True, verbose_name='slug')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='image')),
                ('contenu', ckeditor.fields.RichTextField(verbose_name='contenu')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='description')),
                ('public', models.BooleanField(default=False, verbose_name='public')),
                ('creation', models.DateTimeField(auto_now_add=True, verbose_name='creation')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('pub_date', models.DateTimeField(blank=True, null=True, verbose_name='publish date')),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pharmacien',
            name='nom_pharmacie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Pharmcie'),
        ),
    ]
