# Generated by Django 2.2.12 on 2020-05-28 05:45

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_c', models.CharField(max_length=255, null=True)),
                ('num_lot', models.IntegerField(max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='image')),
                ('exp', models.DateField(null=True)),
                ('ppm', models.FloatField(max_length=100, null=True)),
                ('qte', models.IntegerField(max_length=100, null=True)),
                ('dosage', models.CharField(max_length=255, null=True)),
                ('condtionnement', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='condtionnemen')),
                ('famille', models.CharField(max_length=255, null=True)),
                ('nom_pharmacie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Pharmcie')),
            ],
        ),
    ]
