# Generated by Django 2.2.12 on 2020-05-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_medicament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='num_lot',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='qte',
            field=models.IntegerField(null=True),
        ),
    ]
