# Generated by Django 2.2.12 on 2020-05-28 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200528_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='nom_pharmacie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Pharmcie'),
        ),
    ]
