# Generated by Django 2.2.12 on 2020-05-28 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200528_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicament',
            old_name='nom_pharmacie',
            new_name='nom_pharma',
        ),
    ]
