# Generated by Django 2.2.12 on 2020-05-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20200528_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='nom_c',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
