# Generated by Django 2.2.12 on 2020-05-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20200528_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='nom_c',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
