# Generated by Django 2.2.12 on 2020-05-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20200529_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='image'),
        ),
    ]
