# Generated by Django 2.2.12 on 2020-05-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20200530_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='img'),
        ),
    ]
