# Generated by Django 2.2.12 on 2020-05-30 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20200530_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='img'),
        ),
    ]
