# Generated by Django 2.2.12 on 2020-05-30 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_auto_20200530_0719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte_stock', models.IntegerField(null=True)),
                ('hors_stock', models.IntegerField(null=True)),
                ('alert_qte', models.IntegerField(null=True)),
                ('nom_c', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Medicament')),
            ],
        ),
    ]
