# Generated by Django 2.2.12 on 2020-06-01 15:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='condtionnement',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='condtionnement'),
        ),
    ]
