# Generated by Django 2.2.12 on 2020-06-01 15:04

import ckeditor.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_auto_20200601_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='condtionnement',
            field=ckeditor.fields.RichTextField(default=django.utils.timezone.now, verbose_name='condtionnement'),
            preserve_default=False,
        ),
    ]
