# Generated by Django 2.2.12 on 2020-06-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_fournisseur_nom_pharmacie'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicament',
            name='nom_stock',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
