# Generated by Django 2.2.12 on 2020-06-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_auto_20200605_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicament',
            name='digital',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
