# Generated by Django 2.2.12 on 2020-06-10 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_auto_20200607_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_order',
            new_name='date_orde',
        ),
    ]
