# Generated by Django 2.2.12 on 2020-06-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_auto_20200610_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_orde',
            field=models.DateTimeField(null=True),
        ),
    ]
