# Generated by Django 2.2.12 on 2020-06-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_auto_20200610_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_orde',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
